# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7486c67ba4e1022f8fce4c668e5007e979ddf4d1949eaa2faaab931218634afcc0ab6dfd1012dfc4b07836fcbe9ef318dbe61c6918aad289aad65310e0f64d67

test:
  secret_key_base: 733ecf017daf86633a77c01065ce32e8a3fb290930e0c7ea9455ecba253c5d51ac225206b68cd24febbe2f99b8a964b8e3f609e436f561317ce1934e32b29f4f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
